# Generated by Django 4.2.4 on 2023-10-30 01:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "cpf",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=15)),
                ("cep", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("data_nasc", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Veterinario",
            fields=[
                ("cpf", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "crmv",
                    models.CharField(
                        default=None, max_length=10, primary_key=True, serialize=False
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("endereco", models.CharField(default=None, max_length=100)),
                ("tel", models.CharField(max_length=15)),
                ("cep", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("data_nasc", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raca", models.CharField(max_length=50)),
                ("idade", models.PositiveIntegerField()),
                ("nome", models.CharField(max_length=100)),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_signup.usuario",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FichaDeVacina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vacina", models.CharField(max_length=100)),
                ("data_vacina", models.DateField()),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_signup.pet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinicaVeterinaria",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tel", models.CharField(max_length=15)),
                ("endereco", models.CharField(default=None, max_length=100)),
                ("num", models.PositiveIntegerField()),
                ("cep", models.CharField(max_length=10)),
                ("plano", models.CharField(default=None, max_length=15)),
                ("cnpj", models.CharField(default=None, max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "vet_resp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_signup.veterinario",
                    ),
                ),
            ],
        ),
    ]
