name: Django CI

on:
  push:
  pull_request:

env:
  DJANGO_PROJECT_PATH: "./EngSoft/"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Clear caches
      run: |
        python -m pip cache purge

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        if [ $? -eq 0 ]; then
          ls -l  # List the contents of the current directory to verify venv creation
          source venv/bin/activate  # On Windows, you can use "venv\Scripts\activate"
          pip install --upgrade pip
          pip install -r requirements.txt
        else
          echo "Error: Failed to create virtual environment."
          exit 1
        fi


        runs-on: ubuntu-latest

    - name: Run Django tests
      working-directory: ${{ env.DJANGO_PROJECT_PATH }}
      run: |
        python manage.py test
