name: Django CI

on:
  push:
  pull_request:

env:
  DJANGO_PROJECT_PATH: "./EngSoft/"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]



    steps:
    - name: Clear caches
      run: |
        python -m pip cache purge

    - name: Activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate  # On Windows, you can use "venv\Scripts\activate"

    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures that the "test" job depends on the completion of the "build" job

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Django tests
      working-directory: ${{ env.DJANGO_PROJECT_PATH }}
      run: |
        python manage.py test