name: Deploy

on:
  push:
    branches:
      - develop # devera ser develop ate que o produto entre em release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # permite acessar os diretorios do repositorio
      - uses: akhileshns/heroku-deploy@v3.12.14 # essa eh a action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "petscan-ressurections" # deve ser unico no Heroku
          heroku_email: "petscan.ia.engsoft@gmail.com"

# ref: https://github.com/marketplace/actions/deploy-to-heroku 
