# Generated by Django 4.2.4 on 2023-09-22 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCard',
            fields=[
                ('animal_name', models.CharField(max_length=50, verbose_name='Animal name')),
                ('animal_id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('animal_profile_image', models.ImageField(
                    upload_to='animal_profile_image/', verbose_name='Animal profile image')),
                ('animal_images', models.ImageField(upload_to='animal_image/', verbose_name='Animal images')),
                ('diagnosed_images', models.IntegerField(verbose_name='Diangosed images')),
                ('verified_images', models.IntegerField(verbose_name='Verified images')),
                ('owner_name', models.CharField(max_length=50, verbose_name='Owner name')),
                ('owner_address', models.CharField(max_length=100, verbose_name='Owner address')),
            ],
        ),
    ]
