# Generated by Django 4.2.4 on 2023-09-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcard',
            name='animal_images',
            field=models.ImageField(upload_to='imageupload/static/animal_image/',
                                    verbose_name='Animal images'),
        ),
        migrations.AlterField(
            model_name='animalcard',
            name='animal_profile_image',
            field=models.ImageField(
                upload_to='imageupload/static/animal_profile_image/', verbose_name='Animal profile image'),
        ),
    ]
