# Generated by Django 4.2.4 on 2023-09-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0002_alter_animalcard_animal_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcard',
            name='animal_images',
            field=models.ImageField(upload_to='imageupload/media', verbose_name='Animal images'),
        ),
        migrations.AlterField(
            model_name='animalcard',
            name='animal_profile_image',
            field=models.ImageField(upload_to='imageupload/media',
                                    verbose_name='Animal profile image'),
        ),
        migrations.AlterField(
            model_name='animalcard',
            name='diagnosed_images',
            field=models.IntegerField(null=True, verbose_name='Diangosed images'),
        ),
        migrations.AlterField(
            model_name='animalcard',
            name='verified_images',
            field=models.IntegerField(null=True, verbose_name='Verified images'),
        ),
    ]
