# Generated by Django 4.2.4 on 2023-09-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0003_alter_animalcard_animal_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imageupload/animalimages', verbose_name='Animal image')),
            ],
        ),
        migrations.RemoveField(
            model_name='animalcard',
            name='animal_images',
        ),
        migrations.AlterField(
            model_name='animalcard',
            name='animal_profile_image',
            field=models.ImageField(upload_to='imageupload/animalprofilepic', verbose_name='Animal profile image'),
        ),
        migrations.AddField(
            model_name='animalcard',
            name='animal_images',
            field=models.ManyToManyField(related_name='animal_cards', to='imageupload.animalimage'),
        ),
    ]
