# Generated by Django 4.2.4 on 2023-10-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("imageupload", "0004_animalimage_remove_animalcard_animal_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalimage",
            name="image",
            field=models.ImageField(
                upload_to="imageupload/animalimages", verbose_name="Animal images"
            ),
        ),
    ]
